### ISSUE TITLE
Not up to date with what's live?

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/TypeScript-wiki#171]
Hey, I want to fix a typo (`paragma`) in https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#typescript-28, but this repository seems to be several months old without a change and the branch names do not indicate there is a different working branch from master, all of them seem to be branches for specific things.

The file I am interested in, `What's-new-in-TypeScript.md` is stuck at TS 2.6 whereas the link above is about 2.8. Where is the up to date file?

Can the *Want to contribute to this Wiki?* be redone so that it takes you to the actual source file and not just the wiki repo?

**Comment by mhegazy** [comment]
Should be updated now. 

The problem is that github does not allow contributions to wiki. so we had to fork it in a repo and manually merge it to allow the community to send us contributions. I have updated the wiki from the site instead of using the wiki repo and sync'ing, and that threw things off. will make sure to sync the two in my future edits.
