### ISSUE TITLE
Document output of --generateTrace

### ISSUE THREAD

**Issue by JonasBa** [microsoft/TypeScript-wiki#288]
Hello everyone, happy ny and holidays!

I've recently been using a lot of --generateTrace to debug some performance issues of our codebase (successfully). While doing so, I often used the chrome://tracing along with @amcasey's library (https://github.com/amcasey/ts-analyze-trace). Since I work on a continuous profiling product where we display our own flamegraphs, I've been quietly hoping to add support for tsc traces.

I couldn't find any information of the actual format used, but I suppose it follows https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview, could someone maybe confirm? In the similar vein, having an explanation of the types.json that is generated would also be ❤️ 

Thanks so much!

**Comment by orta** [comment]
Until you get a more definitive answer: I'm pretty sure we try to conform to that format in tracing, with. respect to the types - the code which generates the types is short and readable, it would beat my explanation, it's this file: https://github.com/microsoft/TypeScript/blob/db9e007900238f12afc7a231817cee1b087b037d/src/compiler/tracing.ts

**Comment by JonasBa** [comment]
Thank you for the reply @orta, I think that suffices for now. I'll close the issue, thanks again!

**Comment by amcasey** [comment]
Thanks for your interest!  One small caveat: this functionality isn't mature enough that we're ready to guarantee changes will be backwards compatible.  Obviously, that will be a consideration, since our own tooling needs to continue to work with older TS versions, but it shouldn't be regarded as a contract.

cc @jakebailey who's also thinking about perf tooling.
